"""Head-camera per-link physical properties from Fusion 360 (GLOBAL CNC frame).

SINGLE SOURCE OF TRUTH for the 3 LEFT camera links' mass / COM / inertia. The model
asset head_camera_dual.xml is GENERATED by head_camera_creation.py (frame-on-joint,
via robot_builder), which imports parse_fusion / LEFT_INFO / mirror_180z from here and
rotates these global-frame values into each joint-local frame (Path B). Regenerate with:
    python head_camera_creation.py

This module no longer writes XML itself: the old global-CNC-frame fullinertia emitter
(inertial_xml / build_inertials / write_to_xml / --write) was removed 2026-06-17 — it
injected inertials into bodies-at-identity, the exact frame degeneracy the rebuild
removed. This file only holds the physics, parses it, and prints it for inspection.

HOW TO UPDATE THE PHYSICS
-------------------------
In Fusion, for each of the 3 LEFT links select the components that make up that link
(must match the corresponding .obj grouping):
    base_left      = mount + yaw motor
    yaw_left_link  = neck  + pitch motor
    pitch_left_link= arm   + D435 + U-joint
Open Properties and copy the text in the GLOBAL / assembly coordinate system (the CNC
frame: plate top face z~=0.41, hole centre x=y=0), part in its real assembled pose.
Each block needs Part Name, Mass, Center of Mass, 'Moment of Inertia at Center of Mass'.
Paste into the three string constants below, then regenerate the XML.

The 3 RIGHT links are the left rotated 180 deg about plate-centre z: mass identical;
COM (x,y,z)->(-x,-y,z); inertia R I Rᵀ with R=diag(-1,-1,1) (Ixz,Iyz flip sign).
Sanity: left COMs base (0,-0.064,0.503), yaw (0,-0.064,0.619), pitch (-0.008,-0.062,0.656) m;
camera total mass 1158.3 g (per side 579.1 g).
"""
from __future__ import annotations
import re
import numpy as np

# ── Fusion 360 Properties for the 3 LEFT links (global CNC frame; g/mm or SI ok) ──
base_left_info = """
Part Name	base_left   (mount + yaw motor)
Material Name	(Various)
Physical
	Mass	246.056089815 g
	Volume	156400 mm³
	World X,Y,Z	0.00 mm, 0.00 mm, 0.00 mm
	Center of Mass	-0.004608843 mm, -63.78357687 mm, 502.763346516 mm
	Moment of Inertia at Center of Mass (g mm²)
		ixx	264700
		ixy	19.076554175
		ixz	-15.39095595
		iyx	19.076554175
		iyy	266600
		iyz	19566.79577148
		izx	-15.39095595
		izy	19566.79577148
		izz	75007.859597443
	Moment of Inertia at Origin (g mm²)
		ixx	63460000
		izz	1076000
"""

yaw_left_info = """
Part Name	yaw_left   (neck + pitch motor)
Material Name	(Various)
Physical
	Mass	233.076471852 g
	Volume	100400 mm³
	World X,Y,Z	0.00 mm, 0.00 mm, 0.00 mm
	Center of Mass	-0.001585923 mm, -63.609372512 mm, 619.289910094 mm
	Moment of Inertia at Center of Mass (g mm²)
		ixx	136000
		ixy	-7.735151642
		ixz	68.48918296
		iyx	-7.735151642
		iyy	124500
		iyz	-760.019999439
		izx	68.48918296
		izy	-760.019999439
		izz	63955.753086765
	Moment of Inertia at Origin (g mm²)
		ixx	90470000
		izz	1007000
"""

pitch_left_info = """
Part Name	pitch_left   (arm + D435 + U-joint)
Material Name	(Various)
Physical
	Mass	100.000024698 g
	Volume	71309.77912067 mm³
	World X,Y,Z	0.00 mm, 0.00 mm, 0.00 mm
	Center of Mass	-7.835492207 mm, -62.45157359 mm, 656.224980038 mm
	Moment of Inertia at Center of Mass (g mm²)
		ixx	86080.038477593
		ixy	-3345.488182323
		ixz	4541.4661565
		iyx	-3345.488182323
		iyy	30050.988104961
		iyz	2129.110782251
		izx	4541.4661565
		izy	2129.110782251
		izz	74145.925703773
	Moment of Inertia at Origin (g mm²)
		ixx	43540000
		izz	470300
"""

# left body name (matches the OBJ grouping / creation-script source parts) -> Fusion text
LEFT_INFO = {
    "base_left":       base_left_info,
    "yaw_left_link":   yaw_left_info,
    "pitch_left_link": pitch_left_info,
}

RZ180 = np.diag([-1.0, -1.0, 1.0])  # 180 deg about z


def parse_fusion(info: str):
    """Fusion text -> (mass[kg], com[3] m, I[3x3] kg·m² at COM), global frame.

    Accepts either Fusion unit system and converts to SI:
      mass    g  -> kg (1e-3)        |  kg stays
      length  mm -> m  (1e-3)        |  cm -> m (1e-2)  |  m stays
      inertia g·mm² -> kg·m² (1e-9)  |  kg·m² stays
    """
    if "PASTE" in info or "Mass" not in info:
        raise ValueError("looks like a placeholder — paste the Fusion text first")
    mm = re.search(r'Mass\s+([\d.Ee+]+)\s*(kg|g)\b', info)
    mass = float(mm.group(1)) * (1e-3 if mm.group(2) == 'g' else 1.0)
    cm = re.search(r'Center of Mass\s+([-\d.Ee+]+)\s*(mm|cm|m)\s*,\s*'
                   r'([-\d.Ee+]+)\s*(?:mm|cm|m)\s*,\s*([-\d.Ee+]+)\s*(?:mm|cm|m)', info)
    lscale = {'mm': 1e-3, 'cm': 1e-2, 'm': 1.0}[cm.group(2)]
    com = np.array([float(cm.group(i)) for i in (1, 3, 4)]) * lscale
    hdr = re.search(r'Moment of Inertia at Center of Mass\s*\(([^)]*)\)', info).group(1).replace(' ', '').lower()
    iscale = 1e-9 if hdr.startswith('g') else 1.0   # g·mm² -> kg·m²  (kg·m² starts with 'k')
    sec = re.search(r'Moment of Inertia at Center of Mass.*?Izz\s+[-\d.Ee+]+',
                    info, re.DOTALL | re.IGNORECASE).group(0)
    g = lambda k: float(re.search(rf'\b{k}\s+([-\d.Ee+]+)', sec, re.IGNORECASE).group(1)) * iscale
    I = np.array([[g('Ixx'), g('Ixy'), g('Ixz')],
                  [g('Ixy'), g('Iyy'), g('Iyz')],
                  [g('Ixz'), g('Iyz'), g('Izz')]])
    return mass, com, I


def mirror_180z(mass, com, I):
    """Right link = left rotated 180 deg about plate-centre z."""
    return mass, RZ180 @ com, RZ180 @ I @ RZ180.T


if __name__ == "__main__":
    print("Head-camera link physics (global CNC frame, SI). The XML is generated by")
    print("head_camera_creation.py; this only prints the source physics.\n")
    tot = 0.0
    for body, info in LEFT_INFO.items():
        m, c, I = parse_fusion(info)
        mr, cr, _ = mirror_180z(m, c, I)
        tot += 2 * m
        print(f"  {body:16s} mass={m*1000:6.1f} g  com(m)={np.round(c, 4)}")
        print(f"  {body.replace('left', 'right'):16s} mass={mr*1000:6.1f} g  com(m)={np.round(cr, 4)}  (180z)")
    print(f"\ncamera total mass = {tot*1000:.1f} g  (per side {tot*500:.1f} g)")
