"""Generated by generate_collision_pair_exclusions.py -- do not hand-edit.

Regenerate after any change to humanoid_v21 geometry, joint limits, or gripper
mounting: python -m mj_envs.utils.generate_collision_pair_exclusions
"""

from __future__ import annotations

# Pairs excluded from HUMANOID_V21_MINK_COLLISION_PAIRS. Each entry is pose-invariant
# (always/never active regardless of any joint IK can move -> no avoidance value) or
# provably dominated by another monitored pair (redundant -> dropping loses no coverage).
EXCLUDED_COLLISION_PAIRS: set[frozenset] = {
    frozenset(('shoulder_2_L', 'elbow_L')),  # never-active: constant 0.1120m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'shoulder_2_R')),  # never-active: constant 0.2400m > 0.05m margin, dead weight
    frozenset(('elbow_L', 'wrist_2_L')),  # never-active: constant 0.1015m > 0.05m margin, dead weight
    frozenset(('shoulder_2_R', 'elbow_R')),  # never-active: constant 0.1120m > 0.05m margin, dead weight
    frozenset(('elbow_R', 'wrist_2_R')),  # never-active: constant 0.1015m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'hip_2_R')),  # never-fires: pose-dependent (range 0.0029m) but min 0.1303m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'shoulder_2_L')),  # never-fires: pose-dependent (range 0.0487m) but min 0.3667m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'shoulder_3_L')),  # never-fires: pose-dependent (range 0.2021m) but min 0.3007m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'elbow_L')),  # never-fires: pose-dependent (range 0.4587m) but min 0.1722m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'wrist_1_L')),  # never-fires: pose-dependent (range 0.6241m) but min 0.0916m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'shoulder_2_R')),  # never-fires: pose-dependent (range 0.0449m) but min 0.4105m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'shoulder_3_R')),  # never-fires: pose-dependent (range 0.1931m) but min 0.3503m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'elbow_R')),  # never-fires: pose-dependent (range 0.4423m) but min 0.2292m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'wrist_1_R')),  # never-fires: pose-dependent (range 0.6020m) but min 0.1581m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'wrist_2_R')),  # never-fires: pose-dependent (range 0.7691m) but min 0.0880m > 0.05m margin, dead weight
    frozenset(('hip_2_L', 'wrist_3_R')),  # never-fires: pose-dependent (range 0.8576m) but min 0.0715m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'shoulder_2_L')),  # never-fires: pose-dependent (range 0.0449m) but min 0.4105m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'shoulder_3_L')),  # never-fires: pose-dependent (range 0.1960m) but min 0.3478m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'elbow_L')),  # never-fires: pose-dependent (range 0.4499m) but min 0.2229m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'wrist_1_L')),  # never-fires: pose-dependent (range 0.5996m) but min 0.1590m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'wrist_2_L')),  # never-fires: pose-dependent (range 0.7765m) but min 0.0793m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'shoulder_2_R')),  # never-fires: pose-dependent (range 0.0485m) but min 0.3667m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'shoulder_3_R')),  # never-fires: pose-dependent (range 0.2007m) but min 0.3012m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'elbow_R')),  # never-fires: pose-dependent (range 0.4580m) but min 0.1726m > 0.05m margin, dead weight
    frozenset(('hip_2_R', 'wrist_1_R')),  # never-fires: pose-dependent (range 0.6156m) but min 0.1003m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'wrist_1_L')),  # never-fires: pose-dependent (range 0.1232m) but min 0.0772m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'wrist_2_L')),  # never-fires: pose-dependent (range 0.2155m) but min 0.0820m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'shoulder_3_R')),  # never-fires: pose-dependent (range 0.1096m) but min 0.2194m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'elbow_R')),  # never-fires: pose-dependent (range 0.2561m) but min 0.2019m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'wrist_1_R')),  # never-fires: pose-dependent (range 0.4047m) but min 0.1418m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'wrist_2_R')),  # never-fires: pose-dependent (range 0.5675m) but min 0.0760m > 0.05m margin, dead weight
    frozenset(('shoulder_2_L', 'wrist_3_R')),  # never-fires: pose-dependent (range 0.6645m) but min 0.0548m > 0.05m margin, dead weight
    frozenset(('shoulder_3_L', 'wrist_2_L')),  # never-fires: pose-dependent (range 0.1654m) but min 0.0650m > 0.05m margin, dead weight
    frozenset(('shoulder_3_L', 'shoulder_2_R')),  # never-fires: pose-dependent (range 0.1096m) but min 0.2193m > 0.05m margin, dead weight
    frozenset(('shoulder_3_L', 'shoulder_3_R')),  # never-fires: pose-dependent (range 0.2274m) but min 0.1905m > 0.05m margin, dead weight
    frozenset(('shoulder_3_L', 'elbow_R')),  # never-fires: pose-dependent (range 0.3952m) but min 0.1517m > 0.05m margin, dead weight
    frozenset(('shoulder_3_L', 'wrist_1_R')),  # never-fires: pose-dependent (range 0.5063m) but min 0.1286m > 0.05m margin, dead weight
    frozenset(('shoulder_3_L', 'wrist_2_R')),  # never-fires: pose-dependent (range 0.6610m) but min 0.0710m > 0.05m margin, dead weight
    frozenset(('shoulder_3_L', 'wrist_3_R')),  # never-fires: pose-dependent (range 0.7427m) but min 0.0619m > 0.05m margin, dead weight
    frozenset(('elbow_L', 'wrist_3_L')),  # never-fires: pose-dependent (range 0.0886m) but min 0.0889m > 0.05m margin, dead weight
    frozenset(('elbow_L', ('L_left_rack', 'L_right_rack'))),  # never-fires: pose-dependent (range 0.1900m) but min 0.0568m > 0.05m margin, dead weight
    frozenset(('elbow_L', 'shoulder_2_R')),  # never-fires: pose-dependent (range 0.2564m) but min 0.2016m > 0.05m margin, dead weight
    frozenset(('elbow_L', 'shoulder_3_R')),  # never-fires: pose-dependent (range 0.3868m) but min 0.1602m > 0.05m margin, dead weight
    frozenset(('elbow_L', 'elbow_R')),  # never-fires: pose-dependent (range 0.6070m) but min 0.0690m > 0.05m margin, dead weight
    frozenset(('wrist_1_L', 'shoulder_2_R')),  # never-fires: pose-dependent (range 0.4149m) but min 0.1316m > 0.05m margin, dead weight
    frozenset(('wrist_1_L', 'shoulder_3_R')),  # never-fires: pose-dependent (range 0.5033m) but min 0.1314m > 0.05m margin, dead weight
    frozenset(('wrist_1_L', 'elbow_R')),  # never-fires: pose-dependent (range 0.6903m) but min 0.0729m > 0.05m margin, dead weight
    frozenset(('wrist_2_L', ('L_left_rack', 'L_right_rack'))),  # never-fires: pose-dependent (range 0.0031m) but min 0.0715m > 0.05m margin, dead weight
    frozenset(('wrist_2_L', 'shoulder_2_R')),  # never-fires: pose-dependent (range 0.5896m) but min 0.0540m > 0.05m margin, dead weight
    frozenset(('wrist_2_L', 'shoulder_3_R')),  # never-fires: pose-dependent (range 0.6611m) but min 0.0704m > 0.05m margin, dead weight
    frozenset(('wrist_3_L', 'shoulder_2_R')),  # never-fires: pose-dependent (range 0.6637m) but min 0.0553m > 0.05m margin, dead weight
    frozenset(('shoulder_2_R', 'wrist_1_R')),  # never-fires: pose-dependent (range 0.1232m) but min 0.0772m > 0.05m margin, dead weight
    frozenset(('shoulder_2_R', 'wrist_2_R')),  # never-fires: pose-dependent (range 0.2153m) but min 0.0823m > 0.05m margin, dead weight
    frozenset(('shoulder_3_R', 'wrist_2_R')),  # never-fires: pose-dependent (range 0.1653m) but min 0.0652m > 0.05m margin, dead weight
    frozenset(('elbow_R', 'wrist_3_R')),  # never-fires: pose-dependent (range 0.0886m) but min 0.0888m > 0.05m margin, dead weight
    frozenset(('elbow_R', ('R_left_rack', 'R_right_rack'))),  # never-fires: pose-dependent (range 0.1897m) but min 0.0570m > 0.05m margin, dead weight
    frozenset(('wrist_2_R', ('R_left_rack', 'R_right_rack'))),  # never-fires: pose-dependent (range 0.0031m) but min 0.0715m > 0.05m margin, dead weight
}
