"""Mink-only inverse kinematics for two-armed humanoids.

Public API is identical to ``batched_ik.py`` (``BatchedAnalyticalIK`` alias preserved).
Uses only Mink's MuJoCo QP backend — no Warp, no custom DLS kernels, no capsule repulsion.

Frame convention
----------------
All IK data flow is in the **root body frame** (default ``base_link``). ``pos_targets``,
``quat_targets``, ``actual_ee_pos``, ``actual_ee_quat`` passed to ``solve()`` are all
expressed in that frame. ``_solve_mink`` feeds them directly to
``RelativeFrameTask(root=<root_body>)`` — no world conversion, no dependence on the
freejoint qpos. Readouts ``_last_ee_pos_ik_base`` / ``_last_ee_quat_ik_base`` are
returned in the same root-body frame. This matches the deployment sensor stack
(base-mounted or EE-mounted cameras report directly in body frames) and eliminates
the base-pose estimator (VICON / IMU / odometry) from the IK correctness path.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import List, Literal, Optional, Sequence

import mujoco

EEFrameType = Literal["body", "site"]
_MJ_FRAME_TYPES: dict[str, mujoco.mjtObj] = {
    "body": mujoco.mjtObj.mjOBJ_BODY,
    "site": mujoco.mjtObj.mjOBJ_SITE,
}
import numpy as np
import torch

from mj_envs.utils.humanoid_v21_collision_exclusions import EXCLUDED_COLLISION_PAIRS
from mj_envs.utils.ik_mink_local import (
    CollisionAvoidanceLimit,
    Configuration,
    ConfigurationLimit,
    DofFreezingTask,
    FrameTask,
    InvalidFrame,
    InvalidTarget,
    MinkError,
    NoSolutionFound,
    PostureTask,
    RelativeFrameTask,
    SE3,
    TargetNotSet,
    TaskDefinitionError,
    VelocityLimit,
    solve_ik,
)
from mj_envs.utils.torch_math_utils import (
    _axis_angle_to_quat,
    _quat_conjugate,
    _quat_multiply,
    _quat_to_axis_angle,
    _quat_to_rot_matrix,
)


# The parallel_gripper hand's grasping hardware (racks, beyond the wrist_3 flange) as one
# logical unit per side — resolves to the 6 "*_ikproxy*" proxy capsules/arm generated by
# asset/duke_v2/parallel_gripper/parallel_gripper_creation.py (see _collect_body_geoms).
_GRIPPER_L = ("L_left_rack", "L_right_rack")
_GRIPPER_R = ("R_left_rack", "R_right_rack")

# All bodies in the arm/torso/gripper self-collision region. Legs/feet/camera excluded — no
# reach-related self-collision risk there and irrelevant to arm/gripper collision avoidance.
_SELF_COLLISION_BODIES = [
    "base_link", "waist", "hip_2_L", "hip_2_R",
    "shoulder_2_L", "shoulder_3_L", "elbow_L", "wrist_1_L", "wrist_2_L", "wrist_3_L", _GRIPPER_L,
    "shoulder_2_R", "shoulder_3_R", "elbow_R", "wrist_1_R", "wrist_2_R", "wrist_3_R", _GRIPPER_R,
]

# Parent-child links in the kinematic chain always touch at the joint (not a real collision to
# avoid) and would spuriously saturate the constraint every step if included.
_ADJACENT_BODY_PAIRS = {
    frozenset(p) for p in [
        ("base_link", "waist"), ("waist", "hip_2_L"), ("waist", "hip_2_R"),
        ("base_link", "shoulder_2_L"), ("shoulder_2_L", "shoulder_3_L"), ("shoulder_3_L", "elbow_L"),
        ("elbow_L", "wrist_1_L"), ("wrist_1_L", "wrist_2_L"), ("wrist_2_L", "wrist_3_L"), ("wrist_3_L", _GRIPPER_L),
        ("base_link", "shoulder_2_R"), ("shoulder_2_R", "shoulder_3_R"), ("shoulder_3_R", "elbow_R"),
        ("elbow_R", "wrist_1_R"), ("wrist_1_R", "wrist_2_R"), ("wrist_2_R", "wrist_3_R"), ("wrist_3_R", _GRIPPER_R),
    ]
}

# Every non-adjacent body pair in the self-collision region, generated (not hand-curated).
# A hand-curated list previously missed >60 real-penetrating pairs, confirmed by a 30k-sample
# random joint sweep (2026-07-04, all 14 arm DOFs at full range): own-arm fold-back (e.g.
# GRIPPER_L vs shoulder_3_L, -5cm), cross-arm reach beyond the wrist_3 flange (e.g. GRIPPER_R vs
# shoulder_2_L, -7cm), and flat omissions inconsistent with the covered pattern (base_link vs
# wrist_1_L/R, same magnitude as the already-covered elbow case). Systematic generation can't
# miss a link again when the robot changes. Cost is not a concern: mink's broadphase culling
# made 145 curated pairs cost 0.067ms/call (see mink-upgrade profiling); measured directly on
# the gripper-mounted model after EXCLUDED_COLLISION_PAIRS below (136 raw body-pairs -> 79
# listed -> 140 geom-id combos): mean 0.056ms/call, p99 0.089ms, max 0.123ms.
#
# EXCLUDED_COLLISION_PAIRS additionally drops pairs that add no avoidance value: pose-invariant
# ones (distance doesn't depend on any joint IK can move, either always or never past mink's
# activation margin), pose-dependent ones whose distance still never dips below the margin
# across the sweep (varies with pose but never enough to matter), and ones provably dominated
# by another monitored pair at a proper statistical confidence bound (redundant -- dropping
# loses no coverage). Generated by generate_collision_pair_exclusions.py from a 30k-sample
# joint sweep filtered to physically-reachable (non-self-penetrating) poses; regenerate there
# after any change to geometry, joint limits, or gripper mounting -- do not hand-edit
# humanoid_v21_collision_exclusions.py.
HUMANOID_V21_MINK_COLLISION_PAIRS = [
    (a, b)
    for i, a in enumerate(_SELF_COLLISION_BODIES)
    for b in _SELF_COLLISION_BODIES[i + 1:]
    if frozenset((a, b)) not in _ADJACENT_BODY_PAIRS
    and frozenset((a, b)) not in EXCLUDED_COLLISION_PAIRS
]


_REAL_COLLISION_GROUP = 3  # geom_group convention: real collision-class geoms (contype=1)


def _collect_body_geoms(mj_model, body_name: str) -> list[int]:
    """Geom IDs on `body_name` to use for collision-avoidance: prefer IK-only proxy geoms
    (named ``*_ikproxy*``, e.g. the parallel_gripper rack proxies) if any exist on the body;
    otherwise fall back to real collision-class geoms (``geom_group == 3``). Either way this
    excludes visual-only mesh geoms (group 2, contype 0), which the old "collect everything"
    behavior included as dead weight in every pair.

    Returns [] if `body_name` isn't present on `mj_model` (e.g. a hand-specific body on a
    bare-flange/no-hand model) rather than raising — the pair is then dropped by the empty-list
    check in `_build_mink_geom_pairs`, so hand-specific pairs are simply inert on hand-less
    models instead of crashing IK setup.
    """
    try:
        body_id = mj_model.body(body_name).id
    except KeyError:
        return []
    body_geoms = [i for i in range(mj_model.ngeom) if mj_model.geom_bodyid[i] == body_id]
    proxy_geoms = [i for i in body_geoms if "_ikproxy" in mj_model.geom(i).name]
    if proxy_geoms:
        return proxy_geoms
    return [i for i in body_geoms if mj_model.geom_group[i] == _REAL_COLLISION_GROUP]


def _build_mink_geom_pairs(mj_model, body_pairs, mink=None):
    """Convert body-name collision pairs to Mink geom ID pairs.

    Each side of a pair may be a single body name or a tuple of body names, merged into one
    geom list — e.g. ``("L_left_rack", "L_right_rack")`` expresses "the gripper" as one
    logical unit without duplicating every relationship per rack body. See
    ``_collect_body_geoms`` for the per-body geom-selection rule.
    """
    pairs = []
    for side_a, side_b in body_pairs:
        names_a = (side_a,) if isinstance(side_a, str) else tuple(side_a)
        names_b = (side_b,) if isinstance(side_b, str) else tuple(side_b)
        ga = [g for name in names_a for g in _collect_body_geoms(mj_model, name)]
        gb = [g for name in names_b for g in _collect_body_geoms(mj_model, name)]
        if ga and gb:
            pairs.append((ga, gb))
    return pairs


def _build_local_mink_namespace():
    return SimpleNamespace(
        Configuration=Configuration,
        SE3=SE3,
        FrameTask=FrameTask,
        RelativeFrameTask=RelativeFrameTask,
        PostureTask=PostureTask,
        ConfigurationLimit=ConfigurationLimit,
        VelocityLimit=VelocityLimit,
        CollisionAvoidanceLimit=CollisionAvoidanceLimit,
        DofFreezingTask=DofFreezingTask,
        solve_ik=solve_ik,
        MinkError=MinkError,
        TaskDefinitionError=TaskDefinitionError,
        TargetNotSet=TargetNotSet,
        InvalidFrame=InvalidFrame,
        InvalidTarget=InvalidTarget,
        NoSolutionFound=NoSolutionFound,
    )


def _build_ref_mink_namespace():
    try:
        import mink  # type: ignore

        return mink
    except ImportError as exc:
        raise ImportError(
            "[IK-mink] mink-ref requested but official Mink package not importable. "
            "Install official mink package in current Python environment."
        ) from exc


def _build_hybrid_mink_namespace():
    """Build hybrid Mink namespace: official base with optional local symbol overrides."""
    ref = _build_ref_mink_namespace()
    ns = SimpleNamespace(
        Configuration=getattr(ref, "Configuration"),
        SE3=getattr(ref, "SE3"),
        FrameTask=getattr(ref, "FrameTask"),
        RelativeFrameTask=getattr(ref, "RelativeFrameTask"),
        PostureTask=getattr(ref, "PostureTask"),
        ConfigurationLimit=getattr(ref, "ConfigurationLimit"),
        VelocityLimit=getattr(ref, "VelocityLimit"),
        CollisionAvoidanceLimit=getattr(ref, "CollisionAvoidanceLimit"),
        DofFreezingTask=getattr(ref, "DofFreezingTask"),
        solve_ik=getattr(ref, "solve_ik"),
        MinkError=getattr(ref, "MinkError"),
        TaskDefinitionError=getattr(ref, "TaskDefinitionError"),
        TargetNotSet=getattr(ref, "TargetNotSet"),
        InvalidFrame=getattr(ref, "InvalidFrame"),
        InvalidTarget=getattr(ref, "InvalidTarget"),
        NoSolutionFound=getattr(ref, "NoSolutionFound"),
    )
    local_overrides = {
        "solve_ik": solve_ik,
        "ConfigurationLimit": ConfigurationLimit,
        "VelocityLimit": VelocityLimit,
        "DofFreezingTask": DofFreezingTask,
    }
    for name, value in local_overrides.items():
        setattr(ns, name, value)
    return ns


def _mink_quat_apply(q: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Rotate 3-vector v by wxyz quaternion q (numpy float64)."""
    w, x, y, z = q
    qv = np.array([x, y, z], dtype=np.float64)
    t = 2.0 * np.cross(qv, v)
    return v + w * t + np.cross(qv, t)


def _mink_quat_mul(q1: np.ndarray, q2: np.ndarray) -> np.ndarray:
    """Hamilton product q1 ⊗ q2 for wxyz quaternions (numpy float64)."""
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2
    return np.array(
        [
            w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
            w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
            w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
            w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2,
        ],
        dtype=np.float64,
    )


class MinHeightTask:
    """Soft one-sided EE-height floor relative to root.

    Zero cost/error while compliant (z >= min_height); pulls upward only when
    violated. Target is recomputed every solve iteration as the frame's OWN
    current pose with z clamped up to the floor (x/y/orientation copied through
    unchanged) -- when compliant this is an exact match to the current pose
    (zero error on every axis), so the task never fights the primary EE task on
    paths that stay above the floor. A hard EE-z gate was rejected earlier
    (blocks picking cubes below the floor) -- this is deliberately soft instead.

    Composes an inner RelativeFrameTask (reusing its tested position-cost QP
    math) rather than deriving a new relative-position Jacobian by hand. Must
    be built from the caller's resolved mink namespace (``mink_ns``), not the
    local vendored classes directly -- ``BatchedMinkIK``'s default
    ``mink_source="local"`` actually resolves to the real installed ``mink``
    package for ``Configuration``/``RelativeFrameTask``/``SE3`` (see
    ``_build_hybrid_mink_namespace``), which is required for EE *site* frames
    (the local vendored ``Configuration`` only supports body frames).
    """

    def __init__(
        self,
        mink_ns,
        frame_name: str,
        frame_type: str,
        root_name: str,
        root_type: str,
        min_height: float,
        cost: float,
        lm_damping: float = 0.0,
    ):
        self._mink = mink_ns
        self._inner = mink_ns.RelativeFrameTask(
            frame_name=frame_name,
            frame_type=frame_type,
            root_name=root_name,
            root_type=root_type,
            position_cost=[0.0, 0.0, float(cost)],
            orientation_cost=[0.0, 0.0, 0.0],
            lm_damping=lm_damping,
        )
        self._frame_name, self._frame_type = frame_name, frame_type
        self._root_name, self._root_type = root_name, root_type
        self._min_height = float(min_height)

    def compute_qp_objective(self, configuration):
        T_fr = configuration.get_transform(
            self._frame_name, self._frame_type, self._root_name, self._root_type
        )
        pose = np.array(T_fr.wxyz_xyz, dtype=np.float64, copy=True)
        if pose[6] < self._min_height:
            pose[6] = self._min_height
        self._inner.set_target(self._mink.SE3(wxyz_xyz=pose))
        return self._inner.compute_qp_objective(configuration)


class NearTargetHeightTask:
    """Soft EE-height floor gated on horizontal proximity to the LIVE commanded target.

    Replaces MinHeightTask's fixed root-frame threshold, which MEMORY.md logs as
    structurally superseded: memoryless (re-measures every QP micro-iteration, no
    persistent "stay above" state) and keyed to a fixed value that can't tell
    "still transiting from home" (legitimately low) from "wrongly low near the
    target" (the actual bug). This task instead reads the SAME arm's primary
    RelativeFrameTask's live target every iteration (``ref_task``) and only
    activates when within ``radius`` of that target's x/y AND below
    ``target.z + height_margin`` -- fully inert (target = current pose, zero
    error) during transit or once above the floor, so it never fights the
    primary task outside the pick zone.

    Composes an inner RelativeFrameTask the same way MinHeightTask does (reuses
    tested position-cost QP math); the only new logic is the horizontal-proximity
    gate read off ``ref_task.transform_target_to_root``.
    """

    def __init__(
        self,
        mink_ns,
        ref_task,
        frame_name: str,
        frame_type: str,
        root_name: str,
        root_type: str,
        height_margin: float,
        radius: float,
        cost: float,
        lm_damping: float = 0.0,
    ):
        self._mink = mink_ns
        self._ref_task = ref_task
        self._inner = mink_ns.RelativeFrameTask(
            frame_name=frame_name,
            frame_type=frame_type,
            root_name=root_name,
            root_type=root_type,
            position_cost=[0.0, 0.0, float(cost)],
            orientation_cost=[0.0, 0.0, 0.0],
            lm_damping=lm_damping,
        )
        self._frame_name, self._frame_type = frame_name, frame_type
        self._root_name, self._root_type = root_name, root_type
        self._height_margin = float(height_margin)
        self._radius = float(radius)

    def compute_qp_objective(self, configuration):
        T_fr = configuration.get_transform(
            self._frame_name, self._frame_type, self._root_name, self._root_type
        )
        pose = np.array(T_fr.wxyz_xyz, dtype=np.float64, copy=True)
        ref_target = self._ref_task.transform_target_to_root
        if ref_target is not None:
            target_xyz = np.asarray(ref_target.wxyz_xyz[4:])
            horiz = np.linalg.norm(pose[4:6] - target_xyz[:2])
            floor_z = target_xyz[2] + self._height_margin
            if horiz < self._radius and pose[6] < floor_z:
                pose[6] = floor_z
        self._inner.set_target(self._mink.SE3(wxyz_xyz=pose))
        return self._inner.compute_qp_objective(configuration)


class BatchedMinkIK:
    """Sequential Mink QP IK with the same public tensor API as batched_ik.BatchedAnalyticalIK.

    Solves IK for ``num_envs`` environments one at a time using Mink's QP backend.
    Each call to ``solve()`` runs ``num_iters`` QP steps per environment and returns
    absolute arm joint positions.

    Not thread-safe: ``_mink_config`` is a single shared MjData object mutated in the
    environment loop — do not call ``solve()`` from multiple threads simultaneously.

    State tensors (device)
    ----------------------
    q_ik : (num_envs, nq) float32
        Warm-start qpos for the next solve.  Non-arm DOFs track ``physics_qpos`` each
        step; arm DOFs are updated by the QP solver.  Mutable — use ``reset()`` to
        resync after episode resets rather than writing directly.

    dq_target / ddq_target : (num_envs, 2*K) float32
        Trajectory filter velocity and acceleration; exact filter states, no finite
        differencing.  Read-only outputs; available for feedforward torque use.
    """

    def __init__(
        self,
        mj_model,
        wp_model=None,  # compatibility; accepted positionally but not used
        num_envs: int = 1,
        device: str = "cpu",
        ee_left_name: str = "",
        ee_right_name: str = "",
        left_joint_names: Optional[List[str]] = None,
        right_joint_names: Optional[List[str]] = None,
        ee_left_type: EEFrameType = "body",
        ee_right_type: EEFrameType = "body",
        limit_margin: float = 0.05, # ~ 3 deg
        ki: float = 0.005,
        ki_max: float = 0.05,
        ki_ori: float = 0.005,
        ki_ori_max: float = 0.05,
        ki_decay: float = 0.99, # both for pos/ori integrals
        max_dq: float = 0.5,
        max_target_pos_step: float = 0.005,
        max_target_ori_step_rad: float = 0.05,
        arm_traj_omega: float = 15.0,
        arm_traj_max_dq_out: float = 10.0,
        arm_traj_max_ddq: float = 40.0,
        debug: bool = False,
        step_dt: float = 0.02,
        backend: str = "mink",
        collision_body_pairs: Sequence[tuple[str | Sequence[str], str | Sequence[str]]] = HUMANOID_V21_MINK_COLLISION_PAIRS,
        mink_solver: str = "daqp",
        mink_damping: float = 1e-2,
        mink_lm_damping: float = 2.0,
        mink_position_cost: float = 5.0,
        mink_orientation_cost: Optional[Sequence[float]] = None,
        mink_posture_weight: float = 0.05,
        mink_min_ee_height: Optional[float] = None,
        mink_min_ee_height_cost: float = 1.0,
        mink_min_ee_height_side: Optional[str] = None,
        mink_near_target_height_margin: Optional[float] = None,
        mink_near_target_radius: float = 0.15,
        mink_near_target_height_cost: float = 1.0,
        mink_near_target_height_side: Optional[str] = None,
        collision_min_distance: float = 0.05,
        collision_detection_distance: float = 0.05,
        mink_source: str = "local",
        root_body_name: str = "base_link",
        mink_nosolution_backoff_threshold: int = 3,
        mink_nosolution_cooldown_steps: int = 4,
        use_yaw_frame: bool = True,
        **_batched_ik_compat,  # absorbs unused batched_ik.py kwargs (wp_model, damping, gain, …)
    ):
        """Initialise solver.

        Args:
            mj_model: MuJoCo model (``mujoco.MjModel``).
            num_envs: Number of parallel environments to solve sequentially.
            device: Torch device string for all output tensors.
            ee_left_name: MuJoCo frame name of the left end-effector.
            ee_right_name: MuJoCo frame name of the right end-effector.
            ee_left_type: Frame type for left EE — ``"body"`` or ``"site"``.
            ee_right_type: Frame type for right EE — ``"body"`` or ``"site"``.
            left_joint_names: Ordered left arm joint names (K joints).
            right_joint_names: Ordered right arm joint names (K joints).
            limit_margin: Joint limit safety margin (rad). IK clamps inside
                [lower + margin, upper - margin].
            ki / ki_max: Position integrator gain and per-axis saturation (world frame).
            ki_ori / ki_ori_max: Orientation integrator gain and norm saturation.
            ki_decay: Exponential decay applied to both integrals each step.
            max_dq: Per-joint velocity limit (rad/s) passed to Mink VelocityLimit.
            max_target_pos_step: Max EE position target displacement per step (m).
            max_target_ori_step_rad: Max EE orientation target change per step (rad).
            smooth_near_alpha / smooth_near_thresh / smooth_far_thresh / output_lpf_beta:
                Legacy smoothing params; accepted for call-site compatibility, silently unused.
            arm_traj_omega: Bandwidth (rad/s) of the critically-damped trajectory filter.
                τ ≈ 1/ω; default 15 rad/s → ~67 ms time constant.
            arm_traj_max_dq_out: Max joint velocity (rad/s) in trajectory output.
            arm_traj_max_ddq: Max joint acceleration (rad/s²); directly caps base reaction force.
            debug: Print solver warnings (NoSolutionFound events).
            step_dt: Control timestep (s); used for velocity / acceleration estimation.
            backend: Accepted for API compatibility; must be one of
                ``"mink" | "auto" | "cpu" | "warp"``.
            collision_body_pairs: Body-name pairs for Mink CollisionAvoidanceLimit. Each side
                may be a single body name or a tuple of body names merged into one geom set.
            mink_solver: QP solver name passed to ``mink.solve_ik()`` (e.g. ``"daqp"``).
            mink_damping: Regularisation damping passed to ``mink.solve_ik()``.
            mink_lm_damping: Levenberg-Marquardt damping for FrameTask.
            mink_position_cost: Position tracking cost weight for FrameTask.
            mink_orientation_cost: 3-element orientation cost per axis [x, y, z].
                Defaults to [1.0, 1.0, 0.01] (relaxed wrist-roll).
            mink_posture_weight: PostureTask cost; 0 disables the task entirely.
            mink_min_ee_height: Soft EE-height floor (root/base_link frame, both arms).
                None disables (default, no behavior change). Pulls the EE up only
                when below this z; zero cost/error while compliant, so it never
                blocks a below-floor pick target -- see MinHeightTask docstring.
            mink_min_ee_height_cost: Position-cost weight (z-axis only) for the
                height-floor task when enabled. Unused if mink_min_ee_height is None.
            mink_min_ee_height_side: Restrict the floor to ``"left"`` or ``"right"``;
                None (default) applies to both. The idle arm's resting/folded pose is
                typically well below any reasonable floor, so applying to both would
                continuously fight the idle arm's rest pose every solve iteration --
                pass the reaching side only unless a floor on both arms is intended.
            mink_near_target_height_margin: Soft EE-height floor gated on horizontal
                proximity to the LIVE commanded target (root/base_link frame), not a
                fixed threshold -- see NearTargetHeightTask docstring. None disables
                (default, no behavior change). Replaces mink_min_ee_height's structural
                weakness (memoryless + fixed floor can't discriminate transit-from-home
                vs wrongly-low-near-target); kept as a separate mechanism, not a
                drop-in default, so both can be screened independently.
            mink_near_target_radius: Horizontal (x/y) distance from the live target
                within which the near-target floor can activate. Unused if
                mink_near_target_height_margin is None.
            mink_near_target_height_cost: Position-cost weight (z-axis only) for the
                near-target floor task when enabled. Unused if
                mink_near_target_height_margin is None.
            mink_near_target_height_side: Restrict the near-target floor to ``"left"``
                or ``"right"``; None (default) applies to both. Same idle-arm-fighting
                rationale as mink_min_ee_height_side.
            collision_min_distance: Minimum allowed distance for CollisionAvoidanceLimit.
            collision_detection_distance: Activation range for collision avoidance (m). Default 0.05 — only geom pairs within 5 cm generate QP constraint rows.
            use_yaw_frame: If True, ``quat_targets`` passed to ``solve()`` are interpreted in
                the yaw frame (gravity-aligned, yaw-tracked) rather than root-body frame.
                ``base_quat_wxyz`` must then be provided to ``solve()`` each step so the solver
                can extract the base roll/pitch and convert orientation targets to root-body frame
                before running Mink. Position targets are always root-body frame regardless.
            **_batched_ik_compat: Silently absorbs legacy ``batched_ik.py`` kwargs
                (``wp_model``, ``damping``, ``gain``, ``pos_tol``, etc.) so callers need
                not change their construction call when switching backends.
        """
        # Validation and defaults.
        if left_joint_names is None:
            left_joint_names = []
        if right_joint_names is None:
            right_joint_names = []
        if backend not in ("mink", "auto", "cpu", "warp"):
            raise ValueError(f"Unsupported IK backend '{backend}'. ik_mink.py only supports Mink.")
        if arm_traj_omega <= 0.0:
            raise ValueError(f"arm_traj_omega must be > 0, got {arm_traj_omega}")
        if arm_traj_max_dq_out <= 0.0:
            raise ValueError(f"arm_traj_max_dq_out must be > 0, got {arm_traj_max_dq_out}")
        if arm_traj_max_ddq <= 0.0:
            raise ValueError(f"arm_traj_max_ddq must be > 0, got {arm_traj_max_ddq}")
        if mink_orientation_cost is None:
            mink_orientation_cost = [1.0, 1.0, 0.01]
        if mink_source not in ("local", "ref"):
            raise ValueError(f"Unsupported mink_source '{mink_source}'. Expected 'local' or 'ref'.")
        if mink_nosolution_backoff_threshold < 1:
            raise ValueError(
                f"mink_nosolution_backoff_threshold must be >= 1, got {mink_nosolution_backoff_threshold}"
            )
        if mink_nosolution_cooldown_steps < 0:
            raise ValueError(
                f"mink_nosolution_cooldown_steps must be >= 0, got {mink_nosolution_cooldown_steps}"
            )

        self._use_yaw_frame = bool(use_yaw_frame)

        # Basic runtime state.
        self.mj_model = mj_model
        self.wp_model = None  # compatibility attribute; not used
        self.num_envs = num_envs
        self.device = device
        self.wp_device = str(device)
        self.debug = debug
        self._debug_step = 0
        self.K = len(left_joint_names)
        self._step_dt = float(step_dt)

        # Model IDs and frame anchors.
        self._ee_left_id  = mujoco.mj_name2id(mj_model, _MJ_FRAME_TYPES[ee_left_type],  ee_left_name)
        self._ee_right_id = mujoco.mj_name2id(mj_model, _MJ_FRAME_TYPES[ee_right_type], ee_right_name)
        self._root_body_name = root_body_name
        self._root_body_id = mujoco.mj_name2id(mj_model, mujoco.mjtObj.mjOBJ_BODY, root_body_name)
        if self._ee_left_id == -1:
            raise ValueError(f"[IK-mink] EE {ee_left_type} '{ee_left_name}' not found")
        if self._ee_right_id == -1:
            raise ValueError(f"[IK-mink] EE {ee_right_type} '{ee_right_name}' not found")
        if self._root_body_id == -1:
            raise ValueError(f"[IK-mink] root body '{root_body_name}' not found")
        self._ee_left_name = ee_left_name
        self._ee_right_name = ee_right_name
        self._ee_left_type = ee_left_type
        self._ee_right_type = ee_right_type

        # Joint address maps.
        self._left_qpos_addr = self._qpos_addr(left_joint_names)
        self._right_qpos_addr = self._qpos_addr(right_joint_names)
        self._arm_qpos_addr = torch.cat([self._left_qpos_addr, self._right_qpos_addr])
        self._left_dof_addr = self._dof_addr(left_joint_names)
        self._right_dof_addr = self._dof_addr(right_joint_names)
        self._arm_dof_addr = torch.cat([self._left_dof_addr, self._right_dof_addr])

        # Arm joint limits (raw and IK margin-shrunk).
        all_names = left_joint_names + right_joint_names
        self._joint_lower = torch.tensor(
            [mj_model.joint(j).range[0] for j in all_names],
            dtype=torch.float32,
            device=device,
        )
        self._joint_upper = torch.tensor(
            [mj_model.joint(j).range[1] for j in all_names],
            dtype=torch.float32,
            device=device,
        )
        self._joint_lower_ik = self._joint_lower + limit_margin
        self._joint_upper_ik = self._joint_upper - limit_margin
        self._posture_initialized = False

        # Warm-start qpos and IK saturation state.
        self.q_ik = torch.zeros(num_envs, mj_model.nq, dtype=torch.float32, device=device)
        self._non_arm_mask = torch.ones(mj_model.nq, dtype=torch.bool, device=device)
        self._non_arm_mask[self._arm_qpos_addr] = False
        self._ik_saturated = torch.zeros(num_envs, dtype=torch.bool, device=device)

        # Integrator gains and cached base-frame EE state.
        self._ki = float(ki)
        self._ki_max = float(ki_max)
        self._ki_ori = float(ki_ori)
        self._ki_ori_max = float(ki_ori_max)
        self._ki_decay = float(ki_decay)
        self.ee_integral = torch.zeros(num_envs, 2, 3, dtype=torch.float32, device=device)
        self.ori_integral = torch.zeros(num_envs, 2, 3, dtype=torch.float32, device=device)
        self._last_ee_pos_ik_base = torch.zeros(num_envs, 2, 3, dtype=torch.float32, device=device)
        self._last_ee_quat_ik_base = torch.zeros(num_envs, 2, 4, dtype=torch.float32, device=device)
        self._last_ee_quat_ik_base[..., 0] = 1.0

        # Rate-limited committed EE targets.
        self._max_target_pos_step = float(max_target_pos_step)
        self._pos_targets_committed = torch.zeros(num_envs, 2, 3, dtype=torch.float32, device=device)
        self._pos_target_init_mask = torch.zeros(num_envs, dtype=torch.bool, device=device)
        self._max_target_ori_step_rad = float(max_target_ori_step_rad)
        self._quat_targets_committed = torch.zeros(num_envs, 2, 4, dtype=torch.float32, device=device)
        self._quat_targets_committed[..., 0] = 1.0
        self._quat_target_init_mask = torch.zeros(num_envs, dtype=torch.bool, device=device)

        # Trajectory profile state and outputs.
        self._traj_omega = float(arm_traj_omega)
        self._traj_omega_sq = float(arm_traj_omega) ** 2
        self._traj_2omega = 2.0 * float(arm_traj_omega)
        self._traj_max_dq = float(arm_traj_max_dq_out)
        self._traj_max_ddq = float(arm_traj_max_ddq)
        self._traj_q = torch.zeros(num_envs, 2 * self.K, dtype=torch.float32, device=device)
        self._traj_dq = torch.zeros(num_envs, 2 * self.K, dtype=torch.float32, device=device)
        self.dq_target = torch.zeros(num_envs, 2 * self.K, dtype=torch.float32, device=device)
        self.ddq_target = torch.zeros(num_envs, 2 * self.K, dtype=torch.float32, device=device)

        self._mink = (
            _build_hybrid_mink_namespace()
            if mink_source == "local"
            else _build_ref_mink_namespace()
        )
        # Shared MuJoCo configuration object — mutated per env in the solve loop (not thread-safe).
        self._mink_config = self._mink.Configuration(mj_model)
        self._mink_left_task = self._mink.RelativeFrameTask(
            frame_name=ee_left_name,
            frame_type=ee_left_type,
            root_name=root_body_name,
            root_type="body",
            position_cost=mink_position_cost,
            orientation_cost=mink_orientation_cost,
            lm_damping=mink_lm_damping,
        )
        self._mink_right_task = self._mink.RelativeFrameTask(
            frame_name=ee_right_name,
            frame_type=ee_right_type,
            root_name=root_body_name,
            root_type="body",
            position_cost=mink_position_cost,
            orientation_cost=mink_orientation_cost,
            lm_damping=mink_lm_damping,
        )
        self._mink_use_posture = mink_posture_weight > 0.0
        self._mink_tasks = [self._mink_left_task, self._mink_right_task]
        if self._mink_use_posture:
            self._mink_posture_task = self._mink.PostureTask(mj_model, cost=mink_posture_weight)
            self._mink_posture_task.set_target_from_configuration(self._mink_config)
            self._mink_tasks.append(self._mink_posture_task)

        if mink_min_ee_height is not None:
            assert mink_min_ee_height_side in (None, "left", "right"), mink_min_ee_height_side
            if mink_min_ee_height_side in (None, "left"):
                self._mink_left_height_task = MinHeightTask(
                    self._mink, ee_left_name, ee_left_type, root_body_name, "body",
                    mink_min_ee_height, mink_min_ee_height_cost, lm_damping=mink_lm_damping)
                self._mink_tasks.append(self._mink_left_height_task)
            if mink_min_ee_height_side in (None, "right"):
                self._mink_right_height_task = MinHeightTask(
                    self._mink, ee_right_name, ee_right_type, root_body_name, "body",
                    mink_min_ee_height, mink_min_ee_height_cost, lm_damping=mink_lm_damping)
                self._mink_tasks.append(self._mink_right_height_task)

        if mink_near_target_height_margin is not None:
            assert mink_near_target_height_side in (None, "left", "right"), mink_near_target_height_side
            if mink_near_target_height_side in (None, "left"):
                self._mink_left_near_target_height_task = NearTargetHeightTask(
                    self._mink, self._mink_left_task, ee_left_name, ee_left_type, root_body_name, "body",
                    mink_near_target_height_margin, mink_near_target_radius, mink_near_target_height_cost,
                    lm_damping=mink_lm_damping)
                self._mink_tasks.append(self._mink_left_near_target_height_task)
            if mink_near_target_height_side in (None, "right"):
                self._mink_right_near_target_height_task = NearTargetHeightTask(
                    self._mink, self._mink_right_task, ee_right_name, ee_right_type, root_body_name, "body",
                    mink_near_target_height_margin, mink_near_target_radius, mink_near_target_height_cost,
                    lm_damping=mink_lm_damping)
                self._mink_tasks.append(self._mink_right_near_target_height_task)

        self._mink_limits = [self._mink.ConfigurationLimit(mj_model)]
        if max_dq < float("inf"):
            vel_map = {name: max_dq for name in all_names}
            self._mink_limits.append(self._mink.VelocityLimit(mj_model, velocities=vel_map))
        if collision_body_pairs:
            geom_pairs = _build_mink_geom_pairs(mj_model, collision_body_pairs, self._mink)
            if geom_pairs:
                self._mink_limits.append(
                    self._mink.CollisionAvoidanceLimit(
                        model=mj_model,
                        geom_pairs=geom_pairs,
                        minimum_distance_from_collisions=collision_min_distance,
                        collision_detection_distance=collision_detection_distance,
                    )
                )

        arm_dof_set = set(self._arm_dof_addr.cpu().tolist())
        non_arm_dofs = [dof for dof in range(mj_model.nv) if dof not in arm_dof_set]
        self._mink_constraints = [self._mink.DofFreezingTask(mj_model, dof_indices=non_arm_dofs)]
        self._mink_solver = mink_solver
        self._mink_damping = float(mink_damping)
        self._mink_arm_dof_ids_np = self._arm_dof_addr.cpu().numpy().astype(np.intp)
        self._mink_arm_qpos_ids_np = self._arm_qpos_addr.cpu().numpy().astype(np.intp)
        self._mink_joint_lower_np = self._joint_lower_ik.cpu().numpy()
        self._mink_joint_upper_np = self._joint_upper_ik.cpu().numpy()
        self._mink_nosolution_backoff_threshold = int(mink_nosolution_backoff_threshold)
        self._mink_nosolution_cooldown_steps = int(mink_nosolution_cooldown_steps)
        self._mink_nosolution_streak = np.zeros(self.num_envs, dtype=np.int32)
        self._mink_cooldown_steps_left = np.zeros(self.num_envs, dtype=np.int32)

        # Pre-allocated numpy buffers — reused every solve step to avoid heap allocation.
        # _q_ik_np:      float64 qpos working copy for MuJoCo/Mink (MuJoCo requires float64).
        # _ee_pos_np /   float32 FK results accumulated inside _solve_mink per env, then
        # _ee_quat_np:   bulk-copied to _last_ee_pos/quat_ik_w after the env loop.
        # _se3_{l,r}_buf: [wxyz | xyz] target buffers for FrameTask.set_target(); avoids
        #                 np.concatenate allocation inside the hot inner loop.
        self._q_ik_np = np.zeros((num_envs, mj_model.nq), dtype=np.float64)
        self._ee_pos_np = np.zeros((num_envs, 2, 3), dtype=np.float32)
        self._ee_quat_np = np.zeros((num_envs, 2, 4), dtype=np.float32)
        self._se3_left_buf = np.zeros(7, dtype=np.float64)
        self._se3_right_buf = np.zeros(7, dtype=np.float64)

        print(
            f"[IK-mink] ready: solver={mink_solver}, envs={num_envs}, "
            f"arm_dofs={len(arm_dof_set)}, frozen_dofs={len(non_arm_dofs)}, "
            f"use_yaw_frame={use_yaw_frame}"
        )

    def set_orientation_cost(self, cost) -> None:
        """Set per-axis orientation cost [x, y, z] on both EE tasks. Thread-safe: mink tasks are not shared across threads."""
        self._mink_left_task.set_orientation_cost(cost)
        self._mink_right_task.set_orientation_cost(cost)

    def _qpos_addr(self, names: Sequence[str]) -> torch.Tensor:
        return torch.tensor(
            [int(self.mj_model.joint(name).qposadr[0]) for name in names],
            dtype=torch.long,
            device=self.device,
        )

    def _dof_addr(self, names: Sequence[str]) -> torch.Tensor:
        return torch.tensor(
            [int(self.mj_model.joint(name).dofadr[0]) for name in names],
            dtype=torch.long,
            device=self.device,
        )

    def reset(self, env_ids: torch.Tensor, current_physics_qpos: torch.Tensor):
        """Sync warm-start, integrators, and trajectory-profile state for reset envs."""
        if not self._posture_initialized:
            self._posture_initialized = True
        self.q_ik[env_ids] = current_physics_qpos[env_ids].clone()
        self.ee_integral[env_ids] = 0.0
        self.ori_integral[env_ids] = 0.0
        self._last_ee_pos_ik_base[env_ids] = 0.0
        self._last_ee_quat_ik_base[env_ids] = torch.tensor([1.0, 0.0, 0.0, 0.0], device=self.device)
        self._ik_saturated[env_ids] = False
        arm_q = current_physics_qpos[env_ids][:, self._arm_qpos_addr]
        self._traj_q[env_ids] = arm_q
        self._traj_dq[env_ids] = 0.0
        self._pos_target_init_mask[env_ids] = False
        self._quat_target_init_mask[env_ids] = False
        self.dq_target[env_ids] = 0.0
        self.ddq_target[env_ids] = 0.0
        env_ids_np = env_ids.detach().cpu().numpy()
        self._mink_nosolution_streak[env_ids_np] = 0
        self._mink_cooldown_steps_left[env_ids_np] = 0

        if self._mink_use_posture:
            ref_idx = int(env_ids.flatten()[0].item())
            self._mink_config.data.qpos[:] = current_physics_qpos[ref_idx].detach().cpu().double().numpy()
            self._mink_config.update()
            self._mink_posture_task.set_target_from_configuration(self._mink_config)

    def solve(
        self,
        physics_qpos: torch.Tensor,
        pos_targets: torch.Tensor,
        quat_targets: torch.Tensor,
        num_iters: int = 2,
        actual_ee_pos: Optional[torch.Tensor] = None,
        actual_ee_quat: Optional[torch.Tensor] = None,
        base_quat_wxyz: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """Run Mink IK and return absolute arm joint positions.

        Args:
            physics_qpos: (num_envs, nq) current simulation qpos; used to sync
                non-arm DOFs in the warm start before each solve.
            pos_targets: (num_envs, 2, 3) desired EE positions in **root body frame**.
                Index 0 = left EE, 1 = right EE.
            quat_targets: (num_envs, 2, 4) desired EE orientations. Frame depends on
                ``use_yaw_frame``: root body frame when False (default), yaw frame
                (gravity-aligned, yaw-tracked) when True.
                Index 0 = left EE, 1 = right EE.
            num_iters: QP iterations per environment.  Higher values improve convergence
                but cost proportionally more CPU time.
            actual_ee_pos: (num_envs, 2, 3) observed EE positions in **root body frame**.
                Must match the frame of pos_targets. Drives the position integrator when ki > 0.
            actual_ee_quat: (num_envs, 2, 4) observed EE orientations in **root body frame**,
                wxyz convention. Drives the orientation integrator when ki_ori > 0.
            base_quat_wxyz: (num_envs, 4) or (4,) base orientation in world frame, wxyz
                convention (e.g. from IMU). Required when ``use_yaw_frame=True``; ignored
                otherwise.

        Returns:
            (num_envs, 2*K) absolute arm joint positions, clamped to IK joint limits.
        """
        self.q_ik[:, self._non_arm_mask] = physics_qpos[:, self._non_arm_mask]

        if self._use_yaw_frame:
            if base_quat_wxyz is None:
                raise ValueError("use_yaw_frame=True requires base_quat_wxyz in solve()")
            quat_targets = self._yaw_to_base_quat(quat_targets, base_quat_wxyz)

        pos_targets = self._rate_limit_pos(pos_targets)
        quat_targets = self._rate_limit_quat(quat_targets)
        pos_targets, quat_targets = self._apply_integrators(
            pos_targets, quat_targets, actual_ee_pos, actual_ee_quat
        )

        self._solve_mink(pos_targets, quat_targets, num_iters)

        q_cmd = torch.clamp(
            self.q_ik[:, self._arm_qpos_addr],
            self._joint_lower_ik,
            self._joint_upper_ik,
        )
        self.q_ik[:, self._arm_qpos_addr] = q_cmd

        result = self._apply_trajectory_profile(q_cmd)
        self._update_last_ee_from_smoothed_q(result)
        self._debug_step += 1
        return result

    def _yaw_to_base_quat(
        self, quat_targets: torch.Tensor, base_quat_wxyz: torch.Tensor
    ) -> torch.Tensor:
        """Convert EE orientation targets from yaw frame to root-body frame.

        Yaw frame = world frame with only the yaw (Z-axis) rotation applied; roll and
        pitch are stripped out.  Targets in this frame are gravity-aligned and
        robot-heading-relative, which is natural for manipulation tasks where the base
        tilts under arm loading but the desired grasp orientation should remain fixed
        relative to gravity.

        Derivation:
            q_WY = yaw-only component of q_WB (pure Z rotation)
            q_target_base = q_WB_inv ⊗ q_WY ⊗ q_target_yaw

        Args:
            quat_targets: (num_envs, 2, 4) EE orientation targets in yaw frame, wxyz.
            base_quat_wxyz: (num_envs, 4) or (4,) base orientation in world frame from
                IMU, wxyz convention.

        Returns:
            (num_envs, 2, 4) EE orientation targets in root-body frame.
        """
        if base_quat_wxyz.dim() == 1:
            base_quat_wxyz = base_quat_wxyz.unsqueeze(0)
        base_quat_wxyz = base_quat_wxyz.to(dtype=quat_targets.dtype, device=quat_targets.device)
        w, x, y, z = base_quat_wxyz.unbind(-1)
        yaw = torch.atan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))
        zeros = torch.zeros_like(yaw)
        q_WY = torch.stack([torch.cos(yaw * 0.5), zeros, zeros, torch.sin(yaw * 0.5)], dim=-1)
        q_conv = _quat_multiply(
            _quat_conjugate(base_quat_wxyz), q_WY
        )  # (num_envs, 4): takes yaw-frame vector to base frame
        return _quat_multiply(q_conv.unsqueeze(1).expand_as(quat_targets), quat_targets)

    def _rate_limit_pos(self, pos_targets: torch.Tensor) -> torch.Tensor:
        """Clamp per-step EE position target displacement to ``max_target_pos_step``.

        On first call per environment (before init_mask is set) the raw target is
        committed as-is, avoiding a one-step jump from the zero initialisation.
        """
        init_mask = self._pos_target_init_mask
        if (~init_mask).any():
            self._pos_targets_committed[~init_mask] = pos_targets[~init_mask]
            init_mask[~init_mask] = True
        if self._max_target_pos_step < float("inf"):
            delta = pos_targets - self._pos_targets_committed
            dist = delta.norm(dim=-1, keepdim=True).clamp(min=1e-8)
            scale = (self._max_target_pos_step / dist).clamp(max=1.0)
            self._pos_targets_committed = self._pos_targets_committed + delta * scale
        else:
            self._pos_targets_committed.copy_(pos_targets)
        return self._pos_targets_committed

    def _rate_limit_quat(self, quat_targets: torch.Tensor) -> torch.Tensor:
        """Clamp per-step orientation target change to ``max_target_ori_step_rad``.

        Uses axis-angle magnitude to measure the angular step; limits via slerp-style
        scaling of the delta quaternion before composing with the committed target.
        """
        init_mask = self._quat_target_init_mask
        if (~init_mask).any():
            self._quat_targets_committed[~init_mask] = quat_targets[~init_mask]
            init_mask[~init_mask] = True
        if self._max_target_ori_step_rad < float("inf"):
            q_delta = _quat_multiply(quat_targets, _quat_conjugate(self._quat_targets_committed))
            aa_delta = _quat_to_axis_angle(q_delta)
            ang = aa_delta.norm(dim=-1, keepdim=True).clamp(min=1e-8)
            scale = (self._max_target_ori_step_rad / ang).clamp(max=1.0)
            q_step = _axis_angle_to_quat(aa_delta * scale)
            self._quat_targets_committed = _quat_multiply(q_step, self._quat_targets_committed)
            self._quat_targets_committed = self._quat_targets_committed / self._quat_targets_committed.norm(
                dim=-1, keepdim=True
            ).clamp(min=1e-12)
        else:
            self._quat_targets_committed.copy_(quat_targets)
        return self._quat_targets_committed

    def _apply_integrators(
        self,
        pos_targets: torch.Tensor,
        quat_targets: torch.Tensor,
        actual_ee_pos: Optional[torch.Tensor],
        actual_ee_quat: Optional[torch.Tensor],
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Apply bounded integral correction in root-body frame.

        Error = committed_target - actual_ee. With ki_decay=1.0 this drives actual → committed
        at steady state (integral converges to δ, the model mismatch). Using _last_ee_pos_ik_base
        instead causes integral to ramp unbounded (err = δ constant → integral += ki*δ forever).

        Transient windup (integral accumulates during approach) is bounded by ki_max and ki_decay.
        Keep ki small and ki_decay < 1 to limit overshoot on hardware.

        actual_ee_pos / actual_ee_quat must be in root-body frame (same as pos_targets).
        """
        if actual_ee_pos is not None and self._ki > 0.0:
            err_b = self._pos_targets_committed - actual_ee_pos
            self.ee_integral.mul_(self._ki_decay).add_(self._ki * err_b)
            self.ee_integral.clamp_(-self._ki_max, self._ki_max)
            if self.debug and self._debug_step % 100 == 0:
                L_mm = (self.ee_integral[0, 0] * 1000).detach().cpu().numpy()
                R_mm = (self.ee_integral[0, 1] * 1000).detach().cpu().numpy()
                print(f"[IK-mink] ki_delta step={self._debug_step} L=[{L_mm[0]:.1f},{L_mm[1]:.1f},{L_mm[2]:.1f}]mm R=[{R_mm[0]:.1f},{R_mm[1]:.1f},{R_mm[2]:.1f}]mm")
            pos_targets = pos_targets + self.ee_integral

        if actual_ee_quat is not None and self._ki_ori > 0.0:
            err_aa_b = _quat_to_axis_angle(
                _quat_multiply(self._quat_targets_committed, _quat_conjugate(actual_ee_quat))
            )
            self.ori_integral.mul_(self._ki_decay).add_(self._ki_ori * err_aa_b)
            nrm = self.ori_integral.norm(dim=-1, keepdim=True).clamp(min=1e-8)
            self.ori_integral.mul_(nrm.clamp(max=self._ki_ori_max) / nrm)
            quat_targets = _quat_multiply(_axis_angle_to_quat(self.ori_integral), quat_targets)

        return pos_targets, quat_targets

    def _solve_mink(self, pos_targets: torch.Tensor, quat_targets: torch.Tensor, num_iters: int) -> None:
        """Run sequential Mink IK and refresh cached base-frame EE state.

        Invariants: targets already in root-body frame; freejoint pinned to identity before
        every ``config.update()``; preallocated buffers reused; ``_mink_config`` is shared and
        not re-entrant.
        """
        mink = self._mink
        config = self._mink_config
        data = config.data
        pos_np = pos_targets.detach().cpu().double().numpy()
        quat_np = quat_targets.detach().cpu().double().numpy()
        np.copyto(self._q_ik_np, self.q_ik.detach().cpu().double().numpy())
        ee_l_name = self._ee_left_name
        ee_r_name = self._ee_right_name
        root_name = self._root_body_name

        for env_id in range(self.num_envs):
            cooldown_left = self._mink_cooldown_steps_left[env_id]
            if cooldown_left > 0:
                self._mink_cooldown_steps_left[env_id] = cooldown_left - 1
                continue

            # Target construction: pos/quat already in root body frame.
            self._se3_left_buf[:4] = quat_np[env_id, 0]
            self._se3_left_buf[4:] = pos_np[env_id, 0]
            self._se3_right_buf[:4] = quat_np[env_id, 1]
            self._se3_right_buf[4:] = pos_np[env_id, 1]
            self._mink_left_task.set_target(mink.SE3(wxyz_xyz=self._se3_left_buf))
            self._mink_right_task.set_target(mink.SE3(wxyz_xyz=self._se3_right_buf))

            for _ in range(num_iters):
                np.copyto(data.qpos, self._q_ik_np[env_id])
                # RelativeFrameTask is freejoint-invariant. Pin the local config's
                # freejoint to identity so final FK readout lands in root-body frame.
                if data.qpos.shape[0] >= 7:
                    data.qpos[0:3] = 0.0
                    data.qpos[3] = 1.0
                    data.qpos[4:7] = 0.0
                config.update()

                try:
                    vel = mink.solve_ik(
                        config,
                        self._mink_tasks,
                        dt=1.0,
                        solver=self._mink_solver,
                        damping=self._mink_damping,
                        limits=self._mink_limits,
                        constraints=self._mink_constraints,
                        safety_break=False,
                    )
                    self._mink_nosolution_streak[env_id] = 0
                except (mink.NoSolutionFound, NoSolutionFound):
                    streak = self._mink_nosolution_streak[env_id] + 1
                    self._mink_nosolution_streak[env_id] = streak
                    if streak >= self._mink_nosolution_backoff_threshold:
                        self._mink_cooldown_steps_left[env_id] = self._mink_nosolution_cooldown_steps
                        self._mink_nosolution_streak[env_id] = 0
                        if self.debug:
                            print(
                                f"[IK-mink] NoSolutionFound env={env_id}; entering cooldown "
                                f"{self._mink_nosolution_cooldown_steps} steps"
                            )
                    elif self.debug:
                        print(f"[IK-mink] NoSolutionFound env={env_id}; holding previous pose")
                    continue

                self._q_ik_np[env_id, self._mink_arm_qpos_ids_np] = np.clip(
                    self._q_ik_np[env_id, self._mink_arm_qpos_ids_np] + vel[self._mink_arm_dof_ids_np],
                    self._mink_joint_lower_np,
                    self._mink_joint_upper_np,
                )

            # Final FK with converged qpos; readout is in root-body frame via get_transform.
            np.copyto(data.qpos, self._q_ik_np[env_id])
            if data.qpos.shape[0] >= 7:
                data.qpos[0:3] = 0.0
                data.qpos[3] = 1.0
                data.qpos[4:7] = 0.0
            config.update()
            T_l = config.get_transform(ee_l_name, self._ee_left_type, root_name, "body")
            T_r = config.get_transform(ee_r_name, self._ee_right_type, root_name, "body")
            self._ee_quat_np[env_id, 0] = T_l.wxyz_xyz[:4].astype(np.float32)
            self._ee_pos_np[env_id, 0] = T_l.wxyz_xyz[4:].astype(np.float32)
            self._ee_quat_np[env_id, 1] = T_r.wxyz_xyz[:4].astype(np.float32)
            self._ee_pos_np[env_id, 1] = T_r.wxyz_xyz[4:].astype(np.float32)

        self.q_ik.copy_(torch.from_numpy(self._q_ik_np).float().to(self.device))

    def _apply_trajectory_profile(self, q_cmd: torch.Tensor) -> torch.Tensor:
        """Smooth the raw IK joint command before sending to actuators.

        Instead of jumping straight to q_cmd, the trajectory state (_traj_q,
        _traj_dq) chases it like a mass on a critically-damped spring: it
        accelerates toward the target, then decelerates to stop exactly there
        with no overshoot.

        The acceleration is hard-clamped to max_ddq.  Because arm acceleration
        is what pushes/pulls the robot base (Newton's 3rd law through the
        kinematic chain), this cap directly limits how much the base gets
        disturbed when the arm target changes suddenly.

        Outputs dq_target / ddq_target come straight from the filter state —
        no finite differencing — so they are clean feedforward signals for the
        actuator inverse-dynamics loop.
        """
        dt = self._step_dt
        # Spring acceleration toward target, with velocity damping term.
        # ω² sets how aggressively to chase; 2ω damps to prevent overshoot.
        ddq = self._traj_omega_sq * (q_cmd - self._traj_q)
        ddq.add_(self._traj_dq, alpha=-self._traj_2omega)
        # Hard cap on acceleration — this is the base-disturbance budget.
        ddq.clamp_(-self._traj_max_ddq, self._traj_max_ddq)
        # Euler integrate: velocity then position.
        self._traj_dq.add_(ddq, alpha=dt)
        self._traj_dq.clamp_(-self._traj_max_dq, self._traj_max_dq)
        self._traj_q.add_(self._traj_dq, alpha=dt)
        result = self._traj_q.clamp(self._joint_lower_ik, self._joint_upper_ik)
        self.q_ik[:, self._arm_qpos_addr] = result
        self.dq_target.copy_(self._traj_dq)
        self.ddq_target.copy_(ddq)
        return result

    def _update_last_ee_from_smoothed_q(self, q_cmd: Optional[torch.Tensor] = None) -> None:
        """Recompute base-frame EE pose from smoothed arm command.

        Keep `_last_ee_*_ik_base` aligned with command sent to actuators so
        integrator error is computed against same commanded state.
        """
        config = self._mink_config
        data = config.data
        ee_l_name = self._ee_left_name
        ee_r_name = self._ee_right_name
        root_name = self._root_body_name

        if q_cmd is None:
            np.copyto(self._q_ik_np, self.q_ik.detach().cpu().double().numpy())
        else:
            self._q_ik_np[:, self._mink_arm_qpos_ids_np] = q_cmd.detach().cpu().double().numpy()
        for env_id in range(self.num_envs):
            np.copyto(data.qpos, self._q_ik_np[env_id])
            if data.qpos.shape[0] >= 7:
                data.qpos[0:3] = 0.0
                data.qpos[3] = 1.0
                data.qpos[4:7] = 0.0
            config.update()
            T_l = config.get_transform(ee_l_name, self._ee_left_type, root_name, "body")
            T_r = config.get_transform(ee_r_name, self._ee_right_type, root_name, "body")
            self._ee_quat_np[env_id, 0] = T_l.wxyz_xyz[:4].astype(np.float32)
            self._ee_pos_np[env_id, 0] = T_l.wxyz_xyz[4:].astype(np.float32)
            self._ee_quat_np[env_id, 1] = T_r.wxyz_xyz[:4].astype(np.float32)
            self._ee_pos_np[env_id, 1] = T_r.wxyz_xyz[4:].astype(np.float32)

        self._last_ee_pos_ik_base.copy_(torch.from_numpy(self._ee_pos_np).to(self.device))
        self._last_ee_quat_ik_base.copy_(torch.from_numpy(self._ee_quat_np).to(self.device))


# Alias preserved for callers that import BatchedAnalyticalIK by name.
BatchedAnalyticalIK = BatchedMinkIK

__all__ = [
    "BatchedMinkIK",
    "BatchedAnalyticalIK",
    "HUMANOID_V21_MINK_COLLISION_PAIRS",
    "_build_mink_geom_pairs",
    "MinkError",
    "TaskDefinitionError",
    "TargetNotSet",
    "InvalidFrame",
    "InvalidTarget",
    "NoSolutionFound",
    "SE3",
    "Configuration",
    "FrameTask",
    "RelativeFrameTask",
    "PostureTask",
    "MinHeightTask",
    "NearTargetHeightTask",
    "DofFreezingTask",
    "ConfigurationLimit",
    "VelocityLimit",
    "CollisionAvoidanceLimit",
    "solve_ik",
]
